build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base-python:3.13-alpine3.22
  amd64: ghcr.io/home-assistant/amd64-base-python:3.13-alpine3.22
  i386: ghcr.io/home-assistant/i386-base-python:3.13-alpine3.22