name: "Sites PWA Backend"
version: "1.0.0"
slug: "sitespwa"
description: "Backend API for Sites PWA"
arch:
  - aarch64
  - amd64
  - i386
url: "https://github.com/Jarmo-Jarmo/hassio-addons/tree/main/sitespwa"
init: false
ports:
  443/tcp: 5000
  80/tcp: null
ports_description:
  443/tcp: "Https Web Interface"
  80/tcp: "Web interface"
options:
schema:
image: ghcr.io/jarmo-jarmo/{arch}-sitespwa
