name: Sites PWA Backend
version: "1.0.0"
slug: sitespwa
description: Backend API for Sites PWA
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
url: https://github.com/Jarmo-Jarmo/hassio-addons/tree/main/sitespwa
init: false
options:
  port: 5000
schema:
  port: int(1000, 65535)
image: ghcr.io/home-assistant/{arch}-base-python