name: "Sites PWA Backend"
version: "1.0.0"
slug: "sitespwa"
description: "Backend API for Sites PWA"
arch:
  - aarch64
  - amd64
  - i386
url: "https://github.com/Jarmo-Jarmo/hassio-addons/tree/main/sitespwa"
init: false
options:
  port: 5000
schema:
  port: "int"
image: ghcr.io/jarmo-jarmo/{arch}-sitespwa
