name: ownCloud
version: 1.0.0
slug: owncloud
description: ownCloud personal cloud storage server for Home Assistant
url: https://github.com/Jarmo-Jarmo/hassio-addons/tree/main/owncloud
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
init: false
startup: services
panel_icon: mdi:cloud
panel_title: ownCloud
panel_admin: false
ports:
  80/tcp: 8080
  443/tcp: 8443
ports_description:
  80/tcp: Web interface (HTTP)
  443/tcp: Web interface (HTTPS)
map:
  - share:rw
  - ssl:rw
  - config:rw
  - media:rw
options:
  PUID: 1000
  PGID: 1000
  TZ: America/New_York
  admin_user: admin
  admin_password: ""
  trusted_domains: []
  enable_https: false
  certfile: fullchain.pem
  keyfile: privkey.pem
  database_type: sqlite
  mysql_host: ""
  mysql_database: ""
  mysql_user: ""
  mysql_password: ""
  redis_enabled: false
  redis_host: ""
  redis_password: ""
  log_level: info
  max_upload_size: "512M"
  memory_limit: "512M"
  localmounts: []
  smbmounts: []
  custom_script: ""
schema:
  PUID: int(1000,65000)
  PGID: int(1000,65000)
  TZ: str
  admin_user: str
  admin_password: password
  trusted_domains:
    - str
  enable_https: bool
  certfile: str
  keyfile: str
  database_type: list(sqlite|mysql|pgsql)
  mysql_host: str?
  mysql_database: str?
  mysql_user: str?
  mysql_password: password?
  redis_enabled: bool
  redis_host: str?
  redis_password: password?
  log_level: list(debug|info|warning|error)
  max_upload_size: str
  memory_limit: str
  localmounts:
    - server: str
      mountpoint: str
      username: str?
      password: password?
      workgroup: str?
  smbmounts:
    - server: str
      share: str
      mountpoint: str
      username: str?
      password: password?
      workgroup: str?
  custom_script: str?
image: ghcr.io/jarmo-jarmo/owncloud:latest