name: Build and Push Add-ons (Separate Architectures)

on:
  push:
    branches: [ main, master ]
    paths:
      - 'sitespwa/**'
      - 'owncloud/**'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'sitespwa/**'
      - 'owncloud/**'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  REGISTRY_OWNER: ${{ github.repository_owner }}

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      sitespwa: ${{ steps.changes.outputs.sitespwa }}
      owncloud: ${{ steps.changes.outputs.owncloud }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            sitespwa:
              - 'sitespwa/**'
            owncloud:
              - 'owncloud/**'

  build-addons:
    needs: changes
    runs-on: ubuntu-latest
    strategy:
      matrix:
        addon: [ sitespwa, owncloud ]
        arch: [ amd64, i386, arm64, armv7, armhf ]
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Correctly set BUILD_FROM for each add-on and architecture
      - name: Set BUILD_FROM
        id: buildargs
        run: |
          if [ "${{ matrix.addon }}" = "sitespwa" ]; then
            case "${{ matrix.arch }}" in
              amd64) BUILD_FROM="ghcr.io/home-assistant/amd64-base:3.22" ;;
              i386) BUILD_FROM="ghcr.io/home-assistant/i386-base:3.22" ;;
              arm64) BUILD_FROM="ghcr.io/home-assistant/aarch64-base:3.22" ;;
              armv7) BUILD_FROM="ghcr.io/home-assistant/armv7-base:3.22" ;;
              armhf) BUILD_FROM="ghcr.io/home-assistant/armhf-base:3.22" ;;
            esac
          else
            case "${{ matrix.arch }}" in
              amd64) BUILD_FROM="ghcr.io/home-assistant/amd64-base-python:3.13-alpine3.22" ;;
              i386) BUILD_FROM="ghcr.io/home-assistant/i386-base-python:3.13-alpine3.22" ;;
              arm64) BUILD_FROM="ghcr.io/home-assistant/aarch64-base-python:3.13-alpine3.22" ;;
              armv7) BUILD_FROM="ghcr.io/home-assistant/armv7-base-python:3.13-alpine3.22" ;;
              armhf) BUILD_FROM="ghcr.io/home-assistant/armhf-base-python:3.13-alpine3.22" ;;
            esac
          fi
          echo "BUILD_FROM=${BUILD_FROM}" >> $GITHUB_OUTPUT

      - id: meta
        if: >
          github.event_name == 'workflow_dispatch' ||
          (matrix.addon == 'sitespwa' && needs.changes.outputs.sitespwa == 'true') ||
          (matrix.addon == 'owncloud' && needs.changes.outputs.owncloud == 'true')
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.REGISTRY_OWNER }}/${{ matrix.addon }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}

      - if: steps.meta.conclusion == 'success'
        uses: docker/build-push-action@v5
        with:
          context: ./${{ matrix.addon }}
          file: ./${{ matrix.addon }}/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/${{ matrix.arch }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            BUILD_FROM=${{ steps.buildargs.outputs.BUILD_FROM }}
