name: Build and Push Add-ons

on:
  push:
    branches: [ main, master ]
    paths:
      - 'sitespwa/**'
      - 'owncloud/**'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'sitespwa/**'
      - 'owncloud/**'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  REGISTRY_OWNER: ${{ github.repository_owner }}

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      sitespwa: ${{ steps.changes.outputs.sitespwa }}
      owncloud: ${{ steps.changes.outputs.owncloud }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            sitespwa:
              - 'sitespwa/**'
            owncloud:
              - 'owncloud/**'

  build-addons:
    needs: changes
    runs-on: ubuntu-latest
    strategy:
      matrix:
        addon: [ sitespwa, owncloud ]
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: meta
        if: >
          github.event_name == 'workflow_dispatch' ||
          (matrix.addon == 'sitespwa' && needs.changes.outputs.sitespwa == 'true') ||
          (matrix.addon == 'owncloud' && needs.changes.outputs.owncloud == 'true')
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.REGISTRY_OWNER }}/${{ matrix.addon }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}

      - if: steps.meta.conclusion == 'success'
        uses: docker/build-push-action@v5
        with:
          context: ./${{ matrix.addon }}
          file: ./${{ matrix.addon }}/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/386
          cache-from: type=gha
          cache-to: type=gha,mode=max
